### PR TITLE
Refactor Opcode and Cbopcode to use static methods

### PR DESCRIPTION
**Pull request by ikari7789**
Using an array of anonymous functions seems clunky and hard to maintain.
I've updated both Opcode and Cbopcode to use hard functions that are private static, and should give a slight speed increase.

### CODE REVIEW

**Comment by gabrielrcouto** [comment]
Yes, I agree, this was one of the "bad" things I got when based my code on a JS Emulator.

Just a question: Why static? I think we can construct Opcode (sending Core to constructor) and just call $this->opcode->run($address).

**Comment by ikari7789** [comment]
I started out that way to be honest, but decided to use static as it should have a slight memory decrease and a slight speed increase as it doesn't need to bother with any object management. Considering this is PHP, and not C/C++, I opted for the slightest performance boost over a typical object oriented approach.

Also, as these are just classes of functions and don't need to store any actual data there's no compelling reason to make them an object.

**Comment by gabrielrcouto** [comment]
Well, speed is what we're looking for, let's keep static :+1: 

Could you fix the code to pass on the Travis tests?

And really thank you, you're doing a hard work, the Opcode is a nightmare to edit because of the number of functions.

**Comment by ikari7789** [comment]
Yeah, I'll fix it in the morning. 2AM here in Tokyo now >_<

**Comment by gabrielrcouto** [comment]
Hehe, no problem! We're on the oposite side of the earth, here is 2PM.

**Comment by ikari7789** [comment]
Alright. Fixed.

**Comment by taisel** [comment]
The most ideal would be to convert all the individual functions to a switch. Passing "this" adds unnecessary overhead that was done at the time when browsers ran anonymous function calling faster than a 256 case switch circa 2010. The subsequent GBA emulator done in JS uses a switch based interpreter instead, as browser VMs finally got smarter.

**Comment by taisel** [comment]
Specifically, doing a property based lookup (with proxying "this") for an interpreter is only faster if the VM is being dumb and generating a giant if/else chain for a switch rather than converting the switch to a jump table behind the scenes. Reason being, that the property based lookup often uses some form of hashing strategy, so the overhead per call is a lot lower than going through 100 branches, but much higher still than a pure jump table. I did a lot of benching on this a few years back.

**Comment by ikari7789** [comment]
Except that that is JS, not PHP. The two languages function differently. Anonymous functions just don't have the same performance as defined functions and beyond that, we could easily improve this to take the Core as not a parameter, but as a class variable, therefore removing the need to pass it in. In any case, I think changing it to pass by reference would be the bigger improvement as it wouldn't need to copy the entire object to a new space in memory each time.

**Comment by taisel** [comment]
What I was describing are the solutions that these dynamic language VMs all use, and why the benching numbers came to be. Of course PHP uses a different strategy than Firefox circa 2010 for solving the property lookups behind the scenes, I'm just describing what is theoretically the best way above if the VM can handle such (switch table).

**Comment by taisel** [comment]
A big "if" there, as I don't know if php can convert the switches to jump tables behind the scenes.

**Comment by ikari7789** [comment]
@taisel 

I haven't tested a switch statement based setup yet, but upon just a simple test of 1,000,000 functions (one is declared functions, one is anonymous functions) the speed difference was quiet clear.

``` bash
$ time php -d memory_limit=-1 declared_functions.php
Total: 1000000
Time:  0.23907899856567

real    0m2.642s
user    0m2.250s
sys 0m0.389s
$ time php -d memory_limit=-1 anonymous_functions.php
Total: 1000000
Time:  9.1215388774872

real    0m9.247s
user    0m9.068s
sys 0m0.145s
```

The contents of the files was simple enough:

declared_functions.php

``` php
<?php

class Test
{
    public static function run($object, $function)
    {
        $function = 'test'.$function;
        return Test::$function($object);
    }

    private static function test0($object)
    {
        $object->count++;
    }

    private static function test1($object)
    {
        $object->count++;
    }

    private static function test2($object)
    {
        $object->count++;
    }

    // ...
}

class Object
{
    public $count;

    public function __construct()
    {
        $this->count = 0;
    }
}

$start = microtime(true);

$object = new Object();
for ($i = 0; $i <= 999999; $i++) {
    Test::run($object, $i);
}
echo "Total: {$object->count}".PHP_EOL;

$end = microtime(true);
echo "Time:  ".($end - $start).PHP_EOL;
```

anonymous_functions.php

``` php
<?php

class Test
{
    public $functions;

    public function get()
    {
        return $this->functions;
    }

    public function __construct()
    {
        for ($i = 0; $i <= 999999; $i++) {
            $this->functions[] = function ($object) {
                $object->count++;
            };
        }
    }
}

class Object
{
    public $count;

    public $test;

    public function __construct()
    {
        $test = new Test();
        $this->test = $test->get();
        $this->count = 0;
    }
}

$start = microtime(true);

$object = new Object();
for ($i = 0; $i <= 999999; $i++) {
    $object->test[$i]($object);
}
echo "Total: {$object->count}".PHP_EOL;

$end = microtime(true);
echo "Time:  ".($end - $start).PHP_EOL;
```

**Comment by taisel** [comment]
I wasn't denying the pull request improving things above. What I was trying to imply was switch performance should be tested to see if that's an even better alternative. What I am saying is there should be further research.

**Comment by ikari7789** [comment]
Found a minute to test out a large case statement. Unfortunately, the results are not good :disappointed: 

``` bash
$ time php -d memory_limit=-1 switch_statement.php
Total: 1000000
Time:  2627.1360881329

real    43m48.909s
user    43m31.438s
sys 0m15.962s
```

``` php
<?php

class Test
{
    public static function run($object, $function)
    {
        switch($function) {
            case 0:
                $object->count++;
                break;
            case 1:
                $object->count++;
                break;
            case 2:
                $object->count++;
                break;
            // ...
        }
    }
}
class Object
{
    public $count;

    public function __construct()
    {
        $this->count = 0;
    }
}

$start = microtime(true);

$object = new Object();
for ($i = 0; $i <= 999999; $i++) {
    Test::run($object, $i);
}
echo "Total: {$object->count}".PHP_EOL;

$end = microtime(true);
echo "Time:  ".($end - $start).PHP_EOL;
```

**Pull request merged**
