### PR TITLE
Add vendor/ to .gitignore (and remove vendor/), add composer.lock to the repository

### PR DESCRIPTION
**Pull request by emielmolenaar**
Add vendor/ to .gitignore (and remove vendor/), add composer.lock to the repository.

### CODE REVIEW

**Comment by dannyweeks** [comment]
+1 beat me by 8 minutes :)

**Comment by emielmolenaar** [comment]
:smiley: :+1:

**Comment by gabrielrcouto** [comment]
This task was on my personal task list, hehehe! :+1: Thank you @emielmolenaar

**Comment by emielmolenaar** [comment]
Hehe, nice! :+1:

**Pull request merged**
