### PR TITLE
Adding Help Message

### PR DESCRIPTION
**Pull request by reisraff**

### CODE REVIEW

**Comment by henriquemoody** [comment]
A help message could be something a way more simple but, if that's the intention, I'm really in favor of #27.

**Comment by reisraff** [comment]
@henriquemoody I think like you, but since was added only the help message, it could be merged.

**Comment by henriquemoody** [comment]
I would not merge something I knew I have to change soon... Don't you, @reisraff, want to implement Symfony\Console on this one?

**Comment by reisraff** [comment]
@henriquemoody yeah it would be amazing, and I'll do that as soon, maybe now haha

**Comment by reisraff** [comment]
See #34 PR

**Pull request closed without merging**
