### PR TITLE
Removes copyrighted files from the repository

### PR DESCRIPTION
**Pull request by allyjweir**
Including these games' ROMs could conflict with copyright laws in certain countries/territories. Removing them and following a BYOR (Bring Your Own ROM) policy places the responsibility on the user of the emulator instead of on you for any breaches of copyright.

### CODE REVIEW

**Comment by davelima** [comment]
You're right. In this case, I think that would be good to have a 'How-to configure ROMs' manual, or even a script to convert traditional ROMs into the base64 version of it.

**Comment by pokemaobr** [comment]
Yes, only removing the ROMs we can't support the people to make your ROMs. We need make a 'How-to' as davelima said and then remove the ROMs.

**Comment by ikari7789** [comment]
I'm not sure why base64 encoded ROMs are even required. No one is going to want to do extra work on a ROM before they can use it. Just remove the base64_decode from the ROM loading. It's awkward.

**Comment by gabrielrcouto** [comment]
Good point @allyjweir! I will remove the ROM files and the need of base64 (I used just to don't put the "pure" ROM files on the repository).

A nice idea is to create a "roms" folder, and use something like CLImate to draw a menu for ROM selection. What you guys think about?

**Comment by ikari7789** [comment]
Also, these should be removed permanently via bfg or git-filter branch, not just by a commit. It's important to not leave any trace of these in the repository.

**Comment by ikari7789** [comment]
The idea of a ROMs folder is a great idea I think.

**Comment by ikari7789** [comment]
The GB boot rom should also be removed from Data.php as it's also copyrighted material. Instead it should look for the boot rom file or perhaps passed as a command line argument.

**Comment by coryshaw1** [comment]
Came here to say the same as @ikari7789. The boot rom is also copyrighted, and will need to be apart of the "bring your own" policy. Pretty much all popular emulators require this as well, due to the copyright.

**Comment by ikari7789** [comment]
@gabrielrcouto I've completely removed the copyrighted information in the master branch of my fork. Here's the commands I ran to clean everything up. [BFG](https://rtyley.github.io/bfg-repo-cleaner/) is just a tool to make cleaning up repos easier. This should be done sooner than later as there's already a number of forks that have been made :disappointed:.

``` bash
git rm drmario.rom
git rm megaman.rom
git rm pokemon.rom
git status
git commit -m "Removed copyrighted files."
git push
bfg --delete-files drmario.rom
bfg --delete-files megaman.rom
bfg --delete-files pokemon.rom
git reflog expire --expire=now --all && git gc --prune=now --aggressive
git push --force
cp src/GameBoy/Data.php src/GameBoy/Data.php.bak
git rm src/GameBoy/Data.php
git commit -m 'Removed Data.php with copyrighted material.'
git push
bfg --delete-files Data.php
git reflog expire --expire=now --all && git gc --prune=now --aggressive
git push --force
cp src/GameBoy/Data.php.bak src/GameBoy/Data.php
# Remove bootrom data from Data.php here
vim src/GameBoy/Data.php
git add src/GameBoy/Data.php
git commit -m "Re-added Data.php without copyrighted material."
git push
```

**Comment by allyjweir** [comment]
I would suggest @ikari7789 's solution. I did have a quick look for the boot rom but didn't know what I was looking for.

Action needs to be taken sooner rather than later on this. I don't have time to do it today so am closing this PR

**Comment by gabrielrcouto** [comment]
Done! Thank you very much guys!

@ikari7789 -> A special thank you for you!

**Pull request closed without merging**
